### ISSUE TITLE
Missing three trained TensorFlow Lite models for android

### ISSUE THREAD

**Issue by mustansarsaeed** [spokestack/spokestack-android#104]
Hi, Thank you for the voice pipelines. I couldn't find the three models that you mentioned over github. 

> The wakeword trigger uses three trained TensorFlow Lite models: a filter model for spectrum preprocessing, an autoregressive encoder encode model, and a detect decoder model for keyword classification

Can you please guide where to download?

Thanks

**Comment by space-pope** [comment]
Hi; thanks for letting us know about this—it looks like the links in the readme are outdated. I'll fix that soon, but it's just a file extension change; the current links for the demo models that recognize "Spokestack" as the wakeword are:

[detect](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/detect.tflite)|[encode](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/encode.tflite)|[filter](https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/filter.tflite)

**Comment by mustansarsaeed** [comment]
@space-pope I have included the models you provided. I am getting the following errors.

```
2020-09-18 19:21:46.069 3533-3533/examples.speech W/System.err: Caused by: java.lang.IllegalArgumentException: Contents of /file:/android_asset/filter.tflite does not encode a valid TensorFlow Lite model: Could not open '/file:/android_asset/filter.tflite'.
2020-09-18 19:21:46.069 3533-3533/examples.speech W/System.err: The model is not a valid Flatbuffer file
2020-09-18 19:21:46.069 3533-3533/examples.speech W/System.err:     at NativeInterpreterWrapper.createModel(Native Method)
2020-09-18 19:21:46.070 3533-3533/examples.speech W/System.err:     at NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:47)
2020-09-18 19:21:46.070 3533-3533/examples.speech W/System.err:     at Interpreter.<init>(Interpreter.java:178)
2020-09-18 19:21:46.070 3533-3533/examples.speech W/System.err:     at Interpreter.<init>(Interpreter.java:153)
2020-09-18 19:21:46.070 3533-3533/examples.speech W/System.err:     at io.spokestack.spokestack.tensorflow.TensorflowModel.<init>(TensorflowModel.java:40)
2020-09-18 19:21:46.071 3533-3533/examples.speech W/System.err:     at io.spokestack.spokestack.tensorflow.TensorflowModel$Loader.load(TensorflowModel.java:219)
2020-09-18 19:21:46.071 3533-3533/examples.speech W/System.err:     at io.spokestack.spokestack.wakeword.WakewordTrigger.<init>(WakewordTrigger.java:293)
2020-09-18 19:21:46.072 3533-3533/examples.speech W/System.err:     at io.spokestack.spokestack.wakeword.WakewordTrigger.<init>(WakewordTrigger.java:224)
2020-09-18 19:21:46.073 3533-3533/examples.speech W/System.err: 	... 18 more
```

Can you please check what can be the issue?

**Comment by space-pope** [comment]
`file:///android_asset/...` is a URL, not an absolute path (note the leading slash in the error message, indicating that the system is expecting a file with that name under the root directory.

If you want to include the models in your assets folder, you'll need to decompress them on install before they can be accessed by path and used by Spokestack; see [one of our sample apps](https://github.com/spokestack/android-control-room/blob/master/app/src/main/java/io/spokestack/controlroom/MainActivity.kt#L99-L151) for one way to do this, though you'd probably want to do the file existence checks a little more carefully for production use.

**Comment by mustansarsaeed** [comment]
@space-pope Thanks for the reply. I am using the following configuration:

```
SpeechPipeline pipeline = new SpeechPipeline.Builder()
    .useProfile("io.spokestack.spokestack.profile.TFWakewordGoogleASR")
    .setProperty("wake-filter-path", "<tensorflow-lite-filter-path>")
    .setProperty("wake-encode-path", "<tensorflow-lite-encode-path>")
    .setProperty("wake-detect-path", "<tensorflow-lite-detect-path>")
    .setProperty("wake-threshold", 0.85)
    .setProperty("google-credentials", "<google-credentials>")
    .setProperty("locale", "en-US")
    .build();
```

It is asking for `google-credentials`, does this mean that we can not use detect speech offline? Device should be online to access the features?

**Comment by space-pope** [comment]
For that pipeline profile, yes. That profile uses on-device TensorFlow Lite models for wakeword recognition and Google Cloud Speech for ASR.

To use on-device speech recognition (if your device supports it, and most do these days), try the `io.spokestack.spokestack.profile.TFWakewordAndroidASR` profile instead.

For more information on the ASR providers we support, check out [our ASR documentation](https://www.spokestack.io/docs/Concepts/asr), and let us know if anything's missing.

**Comment by mustansarsaeed** [comment]
Hi @space-pope thank you for the guidance. I am facing following `FlatBuffer` error while loading the model:

**Filenames:**

```
private static final String FILTER_FILENAME = "/sdcard/filter.tflite";
  private static final String ENCODE_FILENAME = "/sdcard/encode.tflite";
  private static final String DETECT_FILENAME = "/sdcard/filter.tflite";
```

**Pipeline configuration:**
```
SpeechPipeline.Builder pipelineBuilder = new SpeechPipeline.Builder()
            .setProperty("wake-filter-path", FILTER_FILENAME)
            .setProperty("wake-encode-path", ENCODE_FILENAME)
            .setProperty("wake-detect-path", DETECT_FILENAME)
            );
```

**TFWakewordAndroidASR**

```
try {
      TFWakewordAndroidASR asr = new TFWakewordAndroidASR();
      SpeechPipeline pipeline = asr.apply(pipelineBuilder).build();
      pipeline.start();
    } catch (Exception e) {
      e.printStackTrace();
    }
```

**Error In Loading model:**

```
 19:41:58.916 11095-11095/examples.speech W/System.err: java.lang.reflect.InvocationTargetException
 19:41:58.916 11095-11095/examples.speech W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
 19:41:58.917 11095-11095/examples.speech W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
 19:41:58.918 11095-11095/examples.speech W/System.err:     at io.spokestack.spokestack.SpeechPipeline.createComponents(SpeechPipeline.java:170)
 19:41:58.919 11095-11095/examples.speech W/System.err:     at io.spokestack.spokestack.SpeechPipeline.start(SpeechPipeline.java:149)
 19:41:58.920 11095-11095/examples.speech W/System.err:     at examples.speech.SpeechActivity.onCreate(SpeechActivity.java:175)
 19:41:58.921 11095-11095/examples.speech W/System.err:     at android.app.Activity.performCreate(Activity.java:7110)
 19:41:58.922 11095-11095/examples.speech W/System.err:     at android.app.Activity.performCreate(Activity.java:7101)
 19:41:58.923 11095-11095/examples.speech W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
 19:41:58.923 11095-11095/examples.speech W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2922)
 19:41:58.924 11095-11095/examples.speech W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3047)
 19:41:58.925 11095-11095/examples.speech W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
 19:41:58.925 11095-11095/examples.speech W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
 19:41:58.926 11095-11095/examples.speech W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
 19:41:58.927 11095-11095/examples.speech W/System.err:     at android.os.Looper.loop(Looper.java:166)
 19:41:58.927 11095-11095/examples.speech W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6861)
 19:41:58.928 11095-11095/examples.speech W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 19:41:58.929 11095-11095/examples.speech W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
 19:41:58.929 11095-11095/examples.speech W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 19:41:58.930 11095-11095/examples.speech W/System.err: Caused by: java.lang.IllegalArgumentException: Contents of /sdcard/filter.tflite does not encode a valid TensorFlow Lite model: Could not open '/sdcard/filter.tflite'.
 19:41:58.931 11095-11095/examples.speech W/System.err: The model is not a valid Flatbuffer file
 19:41:58.932 11095-11095/examples.speech W/System.err:     at NativeInterpreterWrapper.createModel(Native Method)
 19:41:58.932 11095-11095/examples.speech W/System.err:     at NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:47)
 19:41:58.933 11095-11095/examples.speech W/System.err:     at Interpreter.<init>(Interpreter.java:178)
 19:41:58.934 11095-11095/examples.speech W/System.err:     at Interpreter.<init>(Interpreter.java:153)
 19:41:58.935 11095-11095/examples.speech W/System.err:     at io.spokestack.spokestack.tensorflow.TensorflowModel.<init>(TensorflowModel.java:40)
 19:41:58.935 11095-11095/examples.speech W/System.err:     at io.spokestack.spokestack.tensorflow.TensorflowModel$Loader.load(TensorflowModel.java:219)
 19:41:58.936 11095-11095/examples.speech W/System.err:     at io.spokestack.spokestack.wakeword.WakewordTrigger.<init>(WakewordTrigger.java:293)
 19:41:58.937 11095-11095/examples.speech W/System.err:     at io.spokestack.spokestack.wakeword.WakewordTrigger.<init>(WakewordTrigger.java:224)
 19:41:58.937 11095-11095/examples.speech W/System.err: 	... 18 more

```
Can you please guide which is the missing item?

Regards

**Comment by space-pope** [comment]
Hi @mustansarsaeed—the best way to locate these files is to use the Android APIs to resolve absolute filenames. Your code above is telling Spokestack that the models are located at the root of the SD card; it would be highly unusual to store app-specific data there.

If you have access to an Android `Context` where you're setting up Spokestack (which you will if you're doing it in an `Activity`; otherwise you can pass one to wherever setup is happening), use a well-known location like the app's [cache directory](https://developer.android.com/reference/android/content/Context#getCacheDir()) or [files directory](https://developer.android.com/reference/android/content/Context#getFilesDir()) to extract your models to, then pass that entire directory into the Spokestack configuration. This is what the sample app I linked you to the other day does—the models are in `app/src/main/assets` (though they're not stored there in the app's repository), and the linked code extracts them from that directory to a well-known path (the cache dir) and passes it into Spokestack.

**Comment by space-pope** [comment]
By the way, if you're just looking to try out voice recognition and don't need wakeword right now, you could switch over to using the `VADTriggerAndroidASR` or `PushToTalkAndroidASR` profile for now to get you past this configuration hurdle. For the former, all speech is sent through ASR, and for the latter, you have to call `<speechpipeline>.activate()` to start ASR, but it would let you at least test out ASR in your app.
