### ISSUE TITLE
TFWakeWordAzureASR Profile

### ISSUE THREAD

**Issue by rayyan808** [spokestack/spokestack-android#162]
Hello,

Your docs indicate TFWakewordAzureASR to be a valid pipeline profile.

`java.lang.IllegalArgumentException: TFWakewordAzureASR pipeline profile is invalid!`

What is the correct way to call upon the profile?

**Comment by space-pope** [comment]
Profiles are designed like a plugin system to let users create their own and use them without any sort of preregistration, so you need the full class name of your chosen profile. [The Android cookbook](https://www.spokestack.io/docs/android/cookbook#activate-asr-with-any-speech) has an example using the full string name, which is valid, but you can also use methods on the class itself to retrieve the name.

In Kotlin:
```kotlin
Spokestack.Builder()
    .withPipelineProfile(TFWakewordAzureASR::class.qualifiedName)
    // etc
    .build()
```

Java:
```java
new Spokestack.Builder()
    .withPipelineProfile(TFWakewordAzureASR.class.getCanonicalName())
    // etc
    .build();
```

**Comment by rayyan808** [comment]
Using your recommended Kotlin and the skeleton provided for AzureSpeechRecognizer:
`07-21 21:05:44.991  5581  5581 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.elementa.elementa/com.elementa.elementa.MainActivity}: java.lang.IllegalArgumentException: com.elementa.elementa.MainActivity.AzureSpeechRecognizer pipeline profile is invalid!`

**Comment by space-pope** [comment]
Which skeleton are you referring to? The class name for the speech recognizer in your error implies that `AzureSpeechRecognizer` is an inner class in your main activity, which shouldn't be happening, so something else is going on there.

I forgot to mention this in my previous reply, but note that you'll need to set the keys `"locale"`, `"azure-api-key"`, and `"azure-region"` in your builder (via `setProperty()`) as mentioned in [the recognizer's documentation](https://javadoc.io/doc/io.spokestack/spokestack-android/latest/io/spokestack/spokestack/microsoft/AzureSpeechRecognizer.html). The other required keys mentioned there are set by default. This, however, is unrelated to the error you're seeing.

**Comment by rayyan808** [comment]
It is the skeleton provided here (converted to Kotlin using Android Studio): https://github.com/spokestack/spokestack-android/blob/master/src/main/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizer.java,  I have not changed anything from the source code. I have already passed the keys and region into the config, I am not passing the locale parameter I'll add that. The `AzureSpeechRecognizer` is it's own class, though the `SpokestackAdapter` is inner classes of ` MainActivity`.
` private fun buildSpokestack(): Spokestack {
        checkForModels()
        return Spokestack.Builder()
                .withPipelineProfile(AzureSpeechRecognizer::class.qualifiedName)
                .setProperty("azure-api-key", "my_key_is_here")
                .setProperty("azure-region", "west europe")
                .setProperty("wake-detect-path", "$cacheDir/detect.tflite")
                .setProperty("wake-encode-path", "$cacheDir/encode.tflite")
                .setProperty("wake-filter-path", "$cacheDir/filter.tflite")
                .setProperty("nlu-model-path", "$cacheDir/nlu.tflite")
                .setProperty("nlu-metadata-path", "$cacheDir/nlu.json")
                .setProperty("wordpiece-vocab-path", "$cacheDir/vocab.txt")
                .setProperty("spokestack-id", "myid")
                .setProperty("spokestack-secret", "mysecret")
                // `applicationContext` is available inside all `Activity`s
                .withAndroidContext(applicationContext)
                // see the next section; `listener` here inherits from `SpokestackAdapter`
                .addListener(listener)
                .build()
    }`
I've tried removing the applicationContext but that doesnt help

**Comment by rayyan808** [comment]
`
class AzureSpeechRecognizer(speechConfig: SpeechConfig) : SpeechProcessor {
    private val msConfig: com.microsoft.cognitiveservices.speech.SpeechConfig
    private var recognizer: SpeechRecognizer? = null
    private var audioStream: PushAudioInputStream? = null
    private var audioConfig: AudioConfig? = null
    private var active = false

    // Azure speech requires little-endian (wav-format) data, so we buffer
    // audio frames internally to avoid mutating data coming from the speech
    // context
    private val buffer: ByteBuffer
    fun createMsConfig(
            apiKey: String?, region: String?): com.microsoft.cognitiveservices.speech.SpeechConfig {
        val config = fromSubscription(apiKey, region)
        config.setProfanity(ProfanityOption.Raw)
        return config
    }

    override fun reset() {
        close()
    }

    /**
     * releases the resources associated with the recognizer.
     */
    override fun close() {
        if (audioStream != null) {
            audioStream!!.close()
            audioStream = null
        }
        if (recognizer != null) {
            recognizer!!.close()
            recognizer = null
        }
    }

    /**
     * processes a frame of audio.
     *
     * @param speechContext the current speech context
     * @param frame         the audio frame to detect
     *
     * @throws Exception if there is an error performing active recognition.
     */
    @Throws(Exception::class)
    override fun process(speechContext: SpeechContext, frame: ByteBuffer) {
        if (speechContext.isActive && !active) {
            begin(speechContext)
        } else if (!speechContext.isActive && active) {
            commit()
        } else if (speechContext.isActive) {
            bufferFrame(frame)
        }
    }

    fun begin(speechContext: SpeechContext) {
        audioStream = AudioInputStream.createPushStream()
        audioConfig = AudioConfig.fromStreamInput(audioStream)
        recognizer = createRecognizer(speechContext)
        recognizer!!.startContinuousRecognitionAsync()
        active = true

        // send any existing frames into the stream
        for (frame in speechContext.buffer) {
            bufferFrame(frame)
        }
    }

    fun createRecognizer(context: SpeechContext): SpeechRecognizer {
        // factored into a separate method for testing
        val rec = SpeechRecognizer(msConfig, audioConfig)
        listen(rec, context)
        return rec
    }

    private fun listen(rec: SpeechRecognizer, context: SpeechContext) {
        val recognitionListener = RecognitionListener(context)
        rec.recognized.addEventListener(recognitionListener)
        val cancellationListener = CancellationListener(context)
        rec.canceled.addEventListener(cancellationListener)
    }

    fun bufferFrame(frame: ByteBuffer?) {
        if (frame != null) {
            if (buffer.remaining() < frame.capacity()) {
                flush()
            }
            frame.rewind()
            buffer.put(frame)
        }
    }

    @Throws(Exception::class)
    fun commit() {
        // send the end of audio
        flush()
        audioStream!!.close()
        recognizer!!.stopContinuousRecognitionAsync().get()
        recognizer!!.close()
        audioConfig!!.close()
        active = false
    }

    private fun flush() {
        if (buffer.hasArray()) {
            buffer.flip()
            audioStream!!.write(buffer.array())
            buffer.clear()
        }
    }

    /**
     * Listener for Speech SDK recognition events.
     */
    internal class RecognitionListener(private val speechContext: SpeechContext) : EventHandler<SpeechRecognitionEventArgs> {
        override fun onEvent(
                sender: Any,
                recognitionArgs: SpeechRecognitionEventArgs) {
            val reason = recognitionArgs.result.reason
            val transcript = recognitionArgs.result.text
            val isFinal = reason == ResultReason.RecognizedSpeech
            if (transcript != "") {
                if (isFinal) {
                    dispatchResult(transcript, SpeechContext.Event.RECOGNIZE)
                } else if (reason == ResultReason.RecognizingSpeech) {
                    dispatchResult(transcript,
                            SpeechContext.Event.PARTIAL_RECOGNIZE)
                }
            } else if (isFinal) {
                speechContext.dispatch(SpeechContext.Event.TIMEOUT)
            }
        }

        private fun dispatchResult(transcript: String,
                                   event: SpeechContext.Event) {
            speechContext.transcript = transcript
            speechContext.confidence = 1.0
            speechContext.dispatch(event)
        }
    }

    /**
     * Listener for Speech SDK cancellation events.
     */
    internal class CancellationListener(private val speechContext: SpeechContext) : EventHandler<SpeechRecognitionCanceledEventArgs> {
        override fun onEvent(
                sender: Any,
                cancellationArgs: SpeechRecognitionCanceledEventArgs) {
            if (cancellationArgs.reason
                    == CancellationReason.Error) {
                val message = String.format(
                        "%s (error code %s)",
                        cancellationArgs.errorDetails,
                        cancellationArgs.errorCode.name)
                speechContext.error = Exception(message)
                speechContext.dispatch(SpeechContext.Event.ERROR)
            }
        }
    }

    /**
     * initializes a new recognizer instance.
     *
     * @param speechConfig Spokestack speech configuration
     */
    init {
        val apiKey = speechConfig.getString("azure-api-key")
        val region = speechConfig.getString("azure-region")
        val sampleRate = speechConfig.getInteger("sample-rate")
        require(sampleRate == 16000) {
            ("Azure only supports a 16kHz sample rate; found: "
                    + sampleRate)
        }
        buffer = ByteBuffer.allocateDirect(4096)
                .order(ByteOrder.LITTLE_ENDIAN)
        msConfig = createMsConfig(apiKey, region)
    }`

**Comment by space-pope** [comment]
That's not a skeleton; that's the main speech recognizer itself, which can't be used as a pipeline profile. The recognizer is only a [single stage](https://www.spokestack.io/docs/concepts/pipeline-stage) in the pipeline. The [pipeline profiles](https://javadoc.io/static/io.spokestack/spokestack-android/11.4.2/io/spokestack/spokestack/profile/package-summary.html) that _use_ Azure as a speech recognizer end in `AzureASR`, which is why my earlier example used `TFWakewordAzureASR`.

If you can give a little more info on what you're trying to do, we might get to a solution more quickly. This would probably be a better discussion to have [in the forum](https://forum.spokestack.io/c/spokestack-libraries/android/12), as it doesn't look like an issue with the library itself.
