### ISSUE TITLE
Add proguard rules to keep spokestack even when used dynamically

### ISSUE THREAD

**Issue by timmywil** [spokestack/spokestack-android#18]
When a project is minified using proguard, Spokestack classes can get removed unless they are loaded and used up front. Some apps may not want to initialize Spokestack until later (e.g. after authentication). I *think* there's a way to add proguard rules to the project to keep spokestack through minification. For instance, with `-keep class com.pylon.spokestack.** { *; }`.

**Comment by space-pope** [comment]
Thanks for bringing this up. Finally got time to address it; I'll ping back here and close the issue when the fix is released.

**Comment by space-pope** [comment]
Addressed in v.5.0.0.
