### ISSUE TITLE
training tflite model

### ISSUE THREAD

**Issue by cogmeta** [spokestack/spokestack-android#38]
Hi,
Thanks for the pipeline. Any plans to release  the code to train tflite models?

**Comment by space-pope** [comment]
Thanks for reaching out; glad you're finding Spokestack useful! We don't currently have plans to release the wakeword training code, but [our documentation](https://spokestack.io/docs/Concepts/wakeword-models) describes the architecture. If you'd like help developing a custom wakeword, you can get in touch via [our website](https://spokestack.io).
